# Generated by Django 4.2.1 on 2024-02-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCliente', models.CharField(max_length=50, verbose_name='Nombre del cliente')),
            ],
        ),
    ]
